server:
  port: 2323
  servlet:
    session:
      timeout: 60
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.111.190.67:3306/angel?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: kylhtx666
  mvc:
      view:
        suffix: .html
        prefix: /
      static-path-pattern: /static/**
  thymeleaf:
      cache: false
  main:
    # Spring Boot 2.1 需要显式开启bean override
    allow-bean-definition-overriding: true

mybatis:
  type-aliases-package: com.yy.pojo
  mapper-locations: classpath:com/yy/mapping/*Mapper.xml


