package com.yy.dao;

import com.yy.pojo.CategoryMenu;
import com.yy.pojo.CategoryMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface CategoryMenuMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoryMenu
     *
     * @mbggenerated Sun Mar 29 13:35:52 CST 2020
     */
    int countByExample(CategoryMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoryMenu
     *
     * @mbggenerated Sun Mar 29 13:35:52 CST 2020
     */
    int deleteByExample(CategoryMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoryMenu
     *
     * @mbggenerated Sun Mar 29 13:35:52 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoryMenu
     *
     * @mbggenerated Sun Mar 29 13:35:52 CST 2020
     */
    int insert(CategoryMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoryMenu
     *
     * @mbggenerated Sun Mar 29 13:35:52 CST 2020
     */
    int insertSelective(CategoryMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoryMenu
     *
     * @mbggenerated Sun Mar 29 13:35:52 CST 2020
     */
    List<CategoryMenu> selectByExample(CategoryMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoryMenu
     *
     * @mbggenerated Sun Mar 29 13:35:52 CST 2020
     */
    CategoryMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoryMenu
     *
     * @mbggenerated Sun Mar 29 13:35:52 CST 2020
     */
    int updateByExampleSelective(@Param("record") CategoryMenu record, @Param("example") CategoryMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoryMenu
     *
     * @mbggenerated Sun Mar 29 13:35:52 CST 2020
     */
    int updateByExample(@Param("record") CategoryMenu record, @Param("example") CategoryMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoryMenu
     *
     * @mbggenerated Sun Mar 29 13:35:52 CST 2020
     */
    int updateByPrimaryKeySelective(CategoryMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoryMenu
     *
     * @mbggenerated Sun Mar 29 13:35:52 CST 2020
     */
    int updateByPrimaryKey(CategoryMenu record);
}