package com.yy.dao;

import com.yy.pojo.DownloanInfo;
import com.yy.pojo.DownloanInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;


@Repository
public interface DownloanInfoMapper extends repositoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table downloanInfo
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    int countByExample(DownloanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table downloanInfo
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    int deleteByExample(DownloanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table downloanInfo
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table downloanInfo
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    int insert(DownloanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table downloanInfo
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    int insertSelective(DownloanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table downloanInfo
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    List<DownloanInfo> selectByExample(DownloanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table downloanInfo
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    DownloanInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table downloanInfo
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    int updateByExampleSelective(@Param("record") DownloanInfo record, @Param("example") DownloanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table downloanInfo
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    int updateByExample(@Param("record") DownloanInfo record, @Param("example") DownloanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table downloanInfo
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    int updateByPrimaryKeySelective(DownloanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table downloanInfo
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    int updateByPrimaryKey(DownloanInfo record);
    List<DownloanInfo> selectByDown(DownloanInfo downloanInfo);
}