package com.yy.pojo;

public class AdminUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminUserInfo.id
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminUserInfo.workerName
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private String workername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminUserInfo.telNum
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private String telnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminUserInfo.passwd
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminUserInfo.sex
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminUserInfo.id
     *
     * @return the value of adminUserInfo.id
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminUserInfo.id
     *
     * @param id the value for adminUserInfo.id
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminUserInfo.workerName
     *
     * @return the value of adminUserInfo.workerName
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public String getWorkername() {
        return workername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminUserInfo.workerName
     *
     * @param workername the value for adminUserInfo.workerName
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setWorkername(String workername) {
        this.workername = workername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminUserInfo.telNum
     *
     * @return the value of adminUserInfo.telNum
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public String getTelnum() {
        return telnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminUserInfo.telNum
     *
     * @param telnum the value for adminUserInfo.telNum
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setTelnum(String telnum) {
        this.telnum = telnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminUserInfo.passwd
     *
     * @return the value of adminUserInfo.passwd
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminUserInfo.passwd
     *
     * @param passwd the value for adminUserInfo.passwd
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminUserInfo.sex
     *
     * @return the value of adminUserInfo.sex
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminUserInfo.sex
     *
     * @param sex the value for adminUserInfo.sex
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }
}