package com.yy.pojo;

public class CategoryMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categoryMenu.id
     *
     * @mbggenerated Sun Mar 29 20:52:24 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categoryMenu.categoryName
     *
     * @mbggenerated Sun Mar 29 20:52:24 CST 2020
     */
    private String categoryname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categoryMenu.id
     *
     * @return the value of categoryMenu.id
     *
     * @mbggenerated Sun Mar 29 20:52:24 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categoryMenu.id
     *
     * @param id the value for categoryMenu.id
     *
     * @mbggenerated Sun Mar 29 20:52:24 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categoryMenu.categoryName
     *
     * @return the value of categoryMenu.categoryName
     *
     * @mbggenerated Sun Mar 29 20:52:24 CST 2020
     */
    public String getCategoryname() {
        return categoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categoryMenu.categoryName
     *
     * @param categoryname the value for categoryMenu.categoryName
     *
     * @mbggenerated Sun Mar 29 20:52:24 CST 2020
     */
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname;
    }
}