package com.yy.pojo;

import java.util.Date;

public class Collect {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.id
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.userId
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.comId
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer comid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.collectTime
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Date collecttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.id
     *
     * @return the value of collect.id
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.id
     *
     * @param id the value for collect.id
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.userId
     *
     * @return the value of collect.userId
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.userId
     *
     * @param userid the value for collect.userId
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.comId
     *
     * @return the value of collect.comId
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getComid() {
        return comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.comId
     *
     * @param comid the value for collect.comId
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setComid(Integer comid) {
        this.comid = comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.collectTime
     *
     * @return the value of collect.collectTime
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Date getCollecttime() {
        return collecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.collectTime
     *
     * @param collecttime the value for collect.collectTime
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setCollecttime(Date collecttime) {
        this.collecttime = collecttime;
    }
}