package com.yy.pojo;

import java.util.ArrayList;
import java.util.List;

public class CommodityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commodity
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commodity
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commodity
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public CommodityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table commodity
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andComnameIsNull() {
            addCriterion("comName is null");
            return (Criteria) this;
        }

        public Criteria andComnameIsNotNull() {
            addCriterion("comName is not null");
            return (Criteria) this;
        }

        public Criteria andComnameEqualTo(String value) {
            addCriterion("comName =", value, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameNotEqualTo(String value) {
            addCriterion("comName <>", value, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameGreaterThan(String value) {
            addCriterion("comName >", value, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameGreaterThanOrEqualTo(String value) {
            addCriterion("comName >=", value, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameLessThan(String value) {
            addCriterion("comName <", value, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameLessThanOrEqualTo(String value) {
            addCriterion("comName <=", value, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameLike(String value) {
            addCriterion("comName like", value, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameNotLike(String value) {
            addCriterion("comName not like", value, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameIn(List<String> values) {
            addCriterion("comName in", values, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameNotIn(List<String> values) {
            addCriterion("comName not in", values, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameBetween(String value1, String value2) {
            addCriterion("comName between", value1, value2, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameNotBetween(String value1, String value2) {
            addCriterion("comName not between", value1, value2, "comname");
            return (Criteria) this;
        }

        public Criteria andComoripriceIsNull() {
            addCriterion("comOriPrice is null");
            return (Criteria) this;
        }

        public Criteria andComoripriceIsNotNull() {
            addCriterion("comOriPrice is not null");
            return (Criteria) this;
        }

        public Criteria andComoripriceEqualTo(Double value) {
            addCriterion("comOriPrice =", value, "comoriprice");
            return (Criteria) this;
        }

        public Criteria andComoripriceNotEqualTo(Double value) {
            addCriterion("comOriPrice <>", value, "comoriprice");
            return (Criteria) this;
        }

        public Criteria andComoripriceGreaterThan(Double value) {
            addCriterion("comOriPrice >", value, "comoriprice");
            return (Criteria) this;
        }

        public Criteria andComoripriceGreaterThanOrEqualTo(Double value) {
            addCriterion("comOriPrice >=", value, "comoriprice");
            return (Criteria) this;
        }

        public Criteria andComoripriceLessThan(Double value) {
            addCriterion("comOriPrice <", value, "comoriprice");
            return (Criteria) this;
        }

        public Criteria andComoripriceLessThanOrEqualTo(Double value) {
            addCriterion("comOriPrice <=", value, "comoriprice");
            return (Criteria) this;
        }

        public Criteria andComoripriceIn(List<Double> values) {
            addCriterion("comOriPrice in", values, "comoriprice");
            return (Criteria) this;
        }

        public Criteria andComoripriceNotIn(List<Double> values) {
            addCriterion("comOriPrice not in", values, "comoriprice");
            return (Criteria) this;
        }

        public Criteria andComoripriceBetween(Double value1, Double value2) {
            addCriterion("comOriPrice between", value1, value2, "comoriprice");
            return (Criteria) this;
        }

        public Criteria andComoripriceNotBetween(Double value1, Double value2) {
            addCriterion("comOriPrice not between", value1, value2, "comoriprice");
            return (Criteria) this;
        }

        public Criteria andCompriceIsNull() {
            addCriterion("comPrice is null");
            return (Criteria) this;
        }

        public Criteria andCompriceIsNotNull() {
            addCriterion("comPrice is not null");
            return (Criteria) this;
        }

        public Criteria andCompriceEqualTo(Double value) {
            addCriterion("comPrice =", value, "comprice");
            return (Criteria) this;
        }

        public Criteria andCompriceNotEqualTo(Double value) {
            addCriterion("comPrice <>", value, "comprice");
            return (Criteria) this;
        }

        public Criteria andCompriceGreaterThan(Double value) {
            addCriterion("comPrice >", value, "comprice");
            return (Criteria) this;
        }

        public Criteria andCompriceGreaterThanOrEqualTo(Double value) {
            addCriterion("comPrice >=", value, "comprice");
            return (Criteria) this;
        }

        public Criteria andCompriceLessThan(Double value) {
            addCriterion("comPrice <", value, "comprice");
            return (Criteria) this;
        }

        public Criteria andCompriceLessThanOrEqualTo(Double value) {
            addCriterion("comPrice <=", value, "comprice");
            return (Criteria) this;
        }

        public Criteria andCompriceIn(List<Double> values) {
            addCriterion("comPrice in", values, "comprice");
            return (Criteria) this;
        }

        public Criteria andCompriceNotIn(List<Double> values) {
            addCriterion("comPrice not in", values, "comprice");
            return (Criteria) this;
        }

        public Criteria andCompriceBetween(Double value1, Double value2) {
            addCriterion("comPrice between", value1, value2, "comprice");
            return (Criteria) this;
        }

        public Criteria andCompriceNotBetween(Double value1, Double value2) {
            addCriterion("comPrice not between", value1, value2, "comprice");
            return (Criteria) this;
        }

        public Criteria andImgurlIsNull() {
            addCriterion("imgUrl is null");
            return (Criteria) this;
        }

        public Criteria andImgurlIsNotNull() {
            addCriterion("imgUrl is not null");
            return (Criteria) this;
        }

        public Criteria andImgurlEqualTo(String value) {
            addCriterion("imgUrl =", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlNotEqualTo(String value) {
            addCriterion("imgUrl <>", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlGreaterThan(String value) {
            addCriterion("imgUrl >", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlGreaterThanOrEqualTo(String value) {
            addCriterion("imgUrl >=", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlLessThan(String value) {
            addCriterion("imgUrl <", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlLessThanOrEqualTo(String value) {
            addCriterion("imgUrl <=", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlLike(String value) {
            addCriterion("imgUrl like", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlNotLike(String value) {
            addCriterion("imgUrl not like", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlIn(List<String> values) {
            addCriterion("imgUrl in", values, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlNotIn(List<String> values) {
            addCriterion("imgUrl not in", values, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlBetween(String value1, String value2) {
            addCriterion("imgUrl between", value1, value2, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlNotBetween(String value1, String value2) {
            addCriterion("imgUrl not between", value1, value2, "imgurl");
            return (Criteria) this;
        }

        public Criteria andSalenumIsNull() {
            addCriterion("saleNum is null");
            return (Criteria) this;
        }

        public Criteria andSalenumIsNotNull() {
            addCriterion("saleNum is not null");
            return (Criteria) this;
        }

        public Criteria andSalenumEqualTo(Integer value) {
            addCriterion("saleNum =", value, "salenum");
            return (Criteria) this;
        }

        public Criteria andSalenumNotEqualTo(Integer value) {
            addCriterion("saleNum <>", value, "salenum");
            return (Criteria) this;
        }

        public Criteria andSalenumGreaterThan(Integer value) {
            addCriterion("saleNum >", value, "salenum");
            return (Criteria) this;
        }

        public Criteria andSalenumGreaterThanOrEqualTo(Integer value) {
            addCriterion("saleNum >=", value, "salenum");
            return (Criteria) this;
        }

        public Criteria andSalenumLessThan(Integer value) {
            addCriterion("saleNum <", value, "salenum");
            return (Criteria) this;
        }

        public Criteria andSalenumLessThanOrEqualTo(Integer value) {
            addCriterion("saleNum <=", value, "salenum");
            return (Criteria) this;
        }

        public Criteria andSalenumIn(List<Integer> values) {
            addCriterion("saleNum in", values, "salenum");
            return (Criteria) this;
        }

        public Criteria andSalenumNotIn(List<Integer> values) {
            addCriterion("saleNum not in", values, "salenum");
            return (Criteria) this;
        }

        public Criteria andSalenumBetween(Integer value1, Integer value2) {
            addCriterion("saleNum between", value1, value2, "salenum");
            return (Criteria) this;
        }

        public Criteria andSalenumNotBetween(Integer value1, Integer value2) {
            addCriterion("saleNum not between", value1, value2, "salenum");
            return (Criteria) this;
        }

        public Criteria andCollectnumIsNull() {
            addCriterion("collectNum is null");
            return (Criteria) this;
        }

        public Criteria andCollectnumIsNotNull() {
            addCriterion("collectNum is not null");
            return (Criteria) this;
        }

        public Criteria andCollectnumEqualTo(Integer value) {
            addCriterion("collectNum =", value, "collectnum");
            return (Criteria) this;
        }

        public Criteria andCollectnumNotEqualTo(Integer value) {
            addCriterion("collectNum <>", value, "collectnum");
            return (Criteria) this;
        }

        public Criteria andCollectnumGreaterThan(Integer value) {
            addCriterion("collectNum >", value, "collectnum");
            return (Criteria) this;
        }

        public Criteria andCollectnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("collectNum >=", value, "collectnum");
            return (Criteria) this;
        }

        public Criteria andCollectnumLessThan(Integer value) {
            addCriterion("collectNum <", value, "collectnum");
            return (Criteria) this;
        }

        public Criteria andCollectnumLessThanOrEqualTo(Integer value) {
            addCriterion("collectNum <=", value, "collectnum");
            return (Criteria) this;
        }

        public Criteria andCollectnumIn(List<Integer> values) {
            addCriterion("collectNum in", values, "collectnum");
            return (Criteria) this;
        }

        public Criteria andCollectnumNotIn(List<Integer> values) {
            addCriterion("collectNum not in", values, "collectnum");
            return (Criteria) this;
        }

        public Criteria andCollectnumBetween(Integer value1, Integer value2) {
            addCriterion("collectNum between", value1, value2, "collectnum");
            return (Criteria) this;
        }

        public Criteria andCollectnumNotBetween(Integer value1, Integer value2) {
            addCriterion("collectNum not between", value1, value2, "collectnum");
            return (Criteria) this;
        }

        public Criteria andBrowsenumIsNull() {
            addCriterion("browseNum is null");
            return (Criteria) this;
        }

        public Criteria andBrowsenumIsNotNull() {
            addCriterion("browseNum is not null");
            return (Criteria) this;
        }

        public Criteria andBrowsenumEqualTo(Integer value) {
            addCriterion("browseNum =", value, "browsenum");
            return (Criteria) this;
        }

        public Criteria andBrowsenumNotEqualTo(Integer value) {
            addCriterion("browseNum <>", value, "browsenum");
            return (Criteria) this;
        }

        public Criteria andBrowsenumGreaterThan(Integer value) {
            addCriterion("browseNum >", value, "browsenum");
            return (Criteria) this;
        }

        public Criteria andBrowsenumGreaterThanOrEqualTo(Integer value) {
            addCriterion("browseNum >=", value, "browsenum");
            return (Criteria) this;
        }

        public Criteria andBrowsenumLessThan(Integer value) {
            addCriterion("browseNum <", value, "browsenum");
            return (Criteria) this;
        }

        public Criteria andBrowsenumLessThanOrEqualTo(Integer value) {
            addCriterion("browseNum <=", value, "browsenum");
            return (Criteria) this;
        }

        public Criteria andBrowsenumIn(List<Integer> values) {
            addCriterion("browseNum in", values, "browsenum");
            return (Criteria) this;
        }

        public Criteria andBrowsenumNotIn(List<Integer> values) {
            addCriterion("browseNum not in", values, "browsenum");
            return (Criteria) this;
        }

        public Criteria andBrowsenumBetween(Integer value1, Integer value2) {
            addCriterion("browseNum between", value1, value2, "browsenum");
            return (Criteria) this;
        }

        public Criteria andBrowsenumNotBetween(Integer value1, Integer value2) {
            addCriterion("browseNum not between", value1, value2, "browsenum");
            return (Criteria) this;
        }

        public Criteria andIsoutIsNull() {
            addCriterion("isout is null");
            return (Criteria) this;
        }

        public Criteria andIsoutIsNotNull() {
            addCriterion("isout is not null");
            return (Criteria) this;
        }

        public Criteria andIsoutEqualTo(Integer value) {
            addCriterion("isout =", value, "isout");
            return (Criteria) this;
        }

        public Criteria andIsoutNotEqualTo(Integer value) {
            addCriterion("isout <>", value, "isout");
            return (Criteria) this;
        }

        public Criteria andIsoutGreaterThan(Integer value) {
            addCriterion("isout >", value, "isout");
            return (Criteria) this;
        }

        public Criteria andIsoutGreaterThanOrEqualTo(Integer value) {
            addCriterion("isout >=", value, "isout");
            return (Criteria) this;
        }

        public Criteria andIsoutLessThan(Integer value) {
            addCriterion("isout <", value, "isout");
            return (Criteria) this;
        }

        public Criteria andIsoutLessThanOrEqualTo(Integer value) {
            addCriterion("isout <=", value, "isout");
            return (Criteria) this;
        }

        public Criteria andIsoutIn(List<Integer> values) {
            addCriterion("isout in", values, "isout");
            return (Criteria) this;
        }

        public Criteria andIsoutNotIn(List<Integer> values) {
            addCriterion("isout not in", values, "isout");
            return (Criteria) this;
        }

        public Criteria andIsoutBetween(Integer value1, Integer value2) {
            addCriterion("isout between", value1, value2, "isout");
            return (Criteria) this;
        }

        public Criteria andIsoutNotBetween(Integer value1, Integer value2) {
            addCriterion("isout not between", value1, value2, "isout");
            return (Criteria) this;
        }

        public Criteria andReecomIsNull() {
            addCriterion("reecom is null");
            return (Criteria) this;
        }

        public Criteria andReecomIsNotNull() {
            addCriterion("reecom is not null");
            return (Criteria) this;
        }

        public Criteria andReecomEqualTo(Integer value) {
            addCriterion("reecom =", value, "reecom");
            return (Criteria) this;
        }

        public Criteria andReecomNotEqualTo(Integer value) {
            addCriterion("reecom <>", value, "reecom");
            return (Criteria) this;
        }

        public Criteria andReecomGreaterThan(Integer value) {
            addCriterion("reecom >", value, "reecom");
            return (Criteria) this;
        }

        public Criteria andReecomGreaterThanOrEqualTo(Integer value) {
            addCriterion("reecom >=", value, "reecom");
            return (Criteria) this;
        }

        public Criteria andReecomLessThan(Integer value) {
            addCriterion("reecom <", value, "reecom");
            return (Criteria) this;
        }

        public Criteria andReecomLessThanOrEqualTo(Integer value) {
            addCriterion("reecom <=", value, "reecom");
            return (Criteria) this;
        }

        public Criteria andReecomIn(List<Integer> values) {
            addCriterion("reecom in", values, "reecom");
            return (Criteria) this;
        }

        public Criteria andReecomNotIn(List<Integer> values) {
            addCriterion("reecom not in", values, "reecom");
            return (Criteria) this;
        }

        public Criteria andReecomBetween(Integer value1, Integer value2) {
            addCriterion("reecom between", value1, value2, "reecom");
            return (Criteria) this;
        }

        public Criteria andReecomNotBetween(Integer value1, Integer value2) {
            addCriterion("reecom not between", value1, value2, "reecom");
            return (Criteria) this;
        }

        public Criteria andAdminidIsNull() {
            addCriterion("adminId is null");
            return (Criteria) this;
        }

        public Criteria andAdminidIsNotNull() {
            addCriterion("adminId is not null");
            return (Criteria) this;
        }

        public Criteria andAdminidEqualTo(Integer value) {
            addCriterion("adminId =", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidNotEqualTo(Integer value) {
            addCriterion("adminId <>", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidGreaterThan(Integer value) {
            addCriterion("adminId >", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidGreaterThanOrEqualTo(Integer value) {
            addCriterion("adminId >=", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidLessThan(Integer value) {
            addCriterion("adminId <", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidLessThanOrEqualTo(Integer value) {
            addCriterion("adminId <=", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidIn(List<Integer> values) {
            addCriterion("adminId in", values, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidNotIn(List<Integer> values) {
            addCriterion("adminId not in", values, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidBetween(Integer value1, Integer value2) {
            addCriterion("adminId between", value1, value2, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidNotBetween(Integer value1, Integer value2) {
            addCriterion("adminId not between", value1, value2, "adminid");
            return (Criteria) this;
        }

        public Criteria andComurlIsNull() {
            addCriterion("comUrl is null");
            return (Criteria) this;
        }

        public Criteria andComurlIsNotNull() {
            addCriterion("comUrl is not null");
            return (Criteria) this;
        }

        public Criteria andComurlEqualTo(String value) {
            addCriterion("comUrl =", value, "comurl");
            return (Criteria) this;
        }

        public Criteria andComurlNotEqualTo(String value) {
            addCriterion("comUrl <>", value, "comurl");
            return (Criteria) this;
        }

        public Criteria andComurlGreaterThan(String value) {
            addCriterion("comUrl >", value, "comurl");
            return (Criteria) this;
        }

        public Criteria andComurlGreaterThanOrEqualTo(String value) {
            addCriterion("comUrl >=", value, "comurl");
            return (Criteria) this;
        }

        public Criteria andComurlLessThan(String value) {
            addCriterion("comUrl <", value, "comurl");
            return (Criteria) this;
        }

        public Criteria andComurlLessThanOrEqualTo(String value) {
            addCriterion("comUrl <=", value, "comurl");
            return (Criteria) this;
        }

        public Criteria andComurlLike(String value) {
            addCriterion("comUrl like", value, "comurl");
            return (Criteria) this;
        }

        public Criteria andComurlNotLike(String value) {
            addCriterion("comUrl not like", value, "comurl");
            return (Criteria) this;
        }

        public Criteria andComurlIn(List<String> values) {
            addCriterion("comUrl in", values, "comurl");
            return (Criteria) this;
        }

        public Criteria andComurlNotIn(List<String> values) {
            addCriterion("comUrl not in", values, "comurl");
            return (Criteria) this;
        }

        public Criteria andComurlBetween(String value1, String value2) {
            addCriterion("comUrl between", value1, value2, "comurl");
            return (Criteria) this;
        }

        public Criteria andComurlNotBetween(String value1, String value2) {
            addCriterion("comUrl not between", value1, value2, "comurl");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNull() {
            addCriterion("category is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNotNull() {
            addCriterion("category is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(String value) {
            addCriterion("category =", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotEqualTo(String value) {
            addCriterion("category <>", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThan(String value) {
            addCriterion("category >", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("category >=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThan(String value) {
            addCriterion("category <", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThanOrEqualTo(String value) {
            addCriterion("category <=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLike(String value) {
            addCriterion("category like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotLike(String value) {
            addCriterion("category not like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryIn(List<String> values) {
            addCriterion("category in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotIn(List<String> values) {
            addCriterion("category not in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryBetween(String value1, String value2) {
            addCriterion("category between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotBetween(String value1, String value2) {
            addCriterion("category not between", value1, value2, "category");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table commodity
     *
     * @mbggenerated do_not_delete_during_merge Thu Mar 26 14:09:35 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table commodity
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}