package com.yy.pojo;

import java.util.Date;

public class Commodity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.id
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.comName
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private String comname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.comOriPrice
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Double comoriprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.comPrice
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Double comprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.imgUrl
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.saleNum
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer salenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.collectNum
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer collectnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.browseNum
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer browsenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.isout
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer isout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.reecom
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer reecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.adminId
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.comUrl
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private String comurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.category
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.details
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private String details;
    private String userImg;

    private Date insertTime;

    private Date updateTime;
    private String comUser;
    private String comCode;

    public Date getInsertTime() {
        return insertTime;
    }

    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getComCode() {
        return comCode;
    }

    public void setComCode(String comCode) {
        this.comCode = comCode;
    }

    public String getComUser() {
        return comUser;
    }

    public void setComUser(String comUser) {
        this.comUser = comUser;
    }

    public String getUserImg() {
        return userImg;
    }

    public void setUserImg(String userImg) {
        this.userImg = userImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.id
     *
     * @return the value of commodity.id
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.id
     *
     * @param id the value for commodity.id
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.comName
     *
     * @return the value of commodity.comName
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public String getComname() {
        return comname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.comName
     *
     * @param comname the value for commodity.comName
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setComname(String comname) {
        this.comname = comname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.comOriPrice
     *
     * @return the value of commodity.comOriPrice
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Double getComoriprice() {
        return comoriprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.comOriPrice
     *
     * @param comoriprice the value for commodity.comOriPrice
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setComoriprice(Double comoriprice) {
        this.comoriprice = comoriprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.comPrice
     *
     * @return the value of commodity.comPrice
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Double getComprice() {
        return comprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.comPrice
     *
     * @param comprice the value for commodity.comPrice
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setComprice(Double comprice) {
        this.comprice = comprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.imgUrl
     *
     * @return the value of commodity.imgUrl
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.imgUrl
     *
     * @param imgurl the value for commodity.imgUrl
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.saleNum
     *
     * @return the value of commodity.saleNum
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getSalenum() {
        return salenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.saleNum
     *
     * @param salenum the value for commodity.saleNum
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setSalenum(Integer salenum) {
        this.salenum = salenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.collectNum
     *
     * @return the value of commodity.collectNum
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getCollectnum() {
        return collectnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.collectNum
     *
     * @param collectnum the value for commodity.collectNum
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setCollectnum(Integer collectnum) {
        this.collectnum = collectnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.browseNum
     *
     * @return the value of commodity.browseNum
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getBrowsenum() {
        return browsenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.browseNum
     *
     * @param browsenum the value for commodity.browseNum
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setBrowsenum(Integer browsenum) {
        this.browsenum = browsenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.isout
     *
     * @return the value of commodity.isout
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getIsout() {
        return isout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.isout
     *
     * @param isout the value for commodity.isout
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setIsout(Integer isout) {
        this.isout = isout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.reecom
     *
     * @return the value of commodity.reecom
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getReecom() {
        return reecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.reecom
     *
     * @param reecom the value for commodity.reecom
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setReecom(Integer reecom) {
        this.reecom = reecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.comUrl
     *
     * @return the value of commodity.comUrl
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public String getComurl() {
        return comurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.comUrl
     *
     * @param comurl the value for commodity.comUrl
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setComurl(String comurl) {
        this.comurl = comurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.category
     *
     * @return the value of commodity.category
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.category
     *
     * @param category the value for commodity.category
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.details
     *
     * @return the value of commodity.details
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.details
     *
     * @param details the value for commodity.details
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setDetails(String details) {
        this.details = details;
    }


    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }
}