package com.yy.pojo;

import java.util.Date;

public class DownloanInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column downloanInfo.id
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column downloanInfo.userId
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column downloanInfo.downTime
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Date downtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column downloanInfo.comId
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer comid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column downloanInfo.downNum
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer downnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column downloanInfo.id
     *
     * @return the value of downloanInfo.id
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column downloanInfo.id
     *
     * @param id the value for downloanInfo.id
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column downloanInfo.userId
     *
     * @return the value of downloanInfo.userId
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column downloanInfo.userId
     *
     * @param userid the value for downloanInfo.userId
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column downloanInfo.downTime
     *
     * @return the value of downloanInfo.downTime
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Date getDowntime() {
        return downtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column downloanInfo.downTime
     *
     * @param downtime the value for downloanInfo.downTime
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setDowntime(Date downtime) {
        this.downtime = downtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column downloanInfo.comId
     *
     * @return the value of downloanInfo.comId
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getComid() {
        return comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column downloanInfo.comId
     *
     * @param comid the value for downloanInfo.comId
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setComid(Integer comid) {
        this.comid = comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column downloanInfo.downNum
     *
     * @return the value of downloanInfo.downNum
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getDownnum() {
        return downnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column downloanInfo.downNum
     *
     * @param downnum the value for downloanInfo.downNum
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setDownnum(Integer downnum) {
        this.downnum = downnum;
    }
}