package com.yy.pojo;

import java.util.Date;

public class OrderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderInfo.id
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderInfo.buyTime
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Date buytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderInfo.buyMoney
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Double buymoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderInfo.userId
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderInfo.orderNum
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private String ordernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderInfo.orderAmount
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer orderamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderInfo.orderUnit
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Double orderunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderInfo.orderPrice
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Double orderprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderInfo.payState
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer paystate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderInfo.comId
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer comid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderInfo.payTime
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Date paytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderInfo.id
     *
     * @return the value of orderInfo.id
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderInfo.id
     *
     * @param id the value for orderInfo.id
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderInfo.buyTime
     *
     * @return the value of orderInfo.buyTime
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Date getBuytime() {
        return buytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderInfo.buyTime
     *
     * @param buytime the value for orderInfo.buyTime
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setBuytime(Date buytime) {
        this.buytime = buytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderInfo.buyMoney
     *
     * @return the value of orderInfo.buyMoney
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Double getBuymoney() {
        return buymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderInfo.buyMoney
     *
     * @param buymoney the value for orderInfo.buyMoney
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setBuymoney(Double buymoney) {
        this.buymoney = buymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderInfo.userId
     *
     * @return the value of orderInfo.userId
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderInfo.userId
     *
     * @param userid the value for orderInfo.userId
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderInfo.orderNum
     *
     * @return the value of orderInfo.orderNum
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public String getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderInfo.orderNum
     *
     * @param ordernum the value for orderInfo.orderNum
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setOrdernum(String ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderInfo.orderAmount
     *
     * @return the value of orderInfo.orderAmount
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getOrderamount() {
        return orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderInfo.orderAmount
     *
     * @param orderamount the value for orderInfo.orderAmount
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setOrderamount(Integer orderamount) {
        this.orderamount = orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderInfo.orderUnit
     *
     * @return the value of orderInfo.orderUnit
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Double getOrderunit() {
        return orderunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderInfo.orderUnit
     *
     * @param orderunit the value for orderInfo.orderUnit
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setOrderunit(Double orderunit) {
        this.orderunit = orderunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderInfo.orderPrice
     *
     * @return the value of orderInfo.orderPrice
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Double getOrderprice() {
        return orderprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderInfo.orderPrice
     *
     * @param orderprice the value for orderInfo.orderPrice
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setOrderprice(Double orderprice) {
        this.orderprice = orderprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderInfo.payState
     *
     * @return the value of orderInfo.payState
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getPaystate() {
        return paystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderInfo.payState
     *
     * @param paystate the value for orderInfo.payState
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setPaystate(Integer paystate) {
        this.paystate = paystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderInfo.comId
     *
     * @return the value of orderInfo.comId
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getComid() {
        return comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderInfo.comId
     *
     * @param comid the value for orderInfo.comId
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setComid(Integer comid) {
        this.comid = comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderInfo.payTime
     *
     * @return the value of orderInfo.payTime
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderInfo.payTime
     *
     * @param paytime the value for orderInfo.payTime
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }
}