package com.yy.pojo;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.id
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.account
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.workerName
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private String workername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.telNum
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private String telnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.passwd
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.sex
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.isVip
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Integer isvip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.vipTime
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private Date viptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.email
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.id
     *
     * @return the value of userInfo.id
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.id
     *
     * @param id the value for userInfo.id
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.account
     *
     * @return the value of userInfo.account
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.account
     *
     * @param account the value for userInfo.account
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.workerName
     *
     * @return the value of userInfo.workerName
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public String getWorkername() {
        return workername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.workerName
     *
     * @param workername the value for userInfo.workerName
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setWorkername(String workername) {
        this.workername = workername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.telNum
     *
     * @return the value of userInfo.telNum
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public String getTelnum() {
        return telnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.telNum
     *
     * @param telnum the value for userInfo.telNum
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setTelnum(String telnum) {
        this.telnum = telnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.passwd
     *
     * @return the value of userInfo.passwd
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.passwd
     *
     * @param passwd the value for userInfo.passwd
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.sex
     *
     * @return the value of userInfo.sex
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.sex
     *
     * @param sex the value for userInfo.sex
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.isVip
     *
     * @return the value of userInfo.isVip
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Integer getIsvip() {
        return isvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.isVip
     *
     * @param isvip the value for userInfo.isVip
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setIsvip(Integer isvip) {
        this.isvip = isvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.vipTime
     *
     * @return the value of userInfo.vipTime
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public Date getViptime() {
        return viptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.vipTime
     *
     * @param viptime the value for userInfo.vipTime
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setViptime(Date viptime) {
        this.viptime = viptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.email
     *
     * @return the value of userInfo.email
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.email
     *
     * @param email the value for userInfo.email
     *
     * @mbggenerated Thu Mar 26 14:09:35 CST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }
}